### ISSUE TITLE
how to match different URl and method

### ISSUE THREAD

**Issue by LuoPQ** [berniegp/mock-xmlhttprequest#1]

**Comment by berniegp** [comment]
What are you trying to do exactly?

**Comment by LuoPQ** [comment]
for example, I want to mock the request with this url "http://a", don't want to mock with this url "http://b", how should I do?

**Comment by berniegp** [comment]
This is not supported.

I can't see a clean way to support this because the MockXMLHttpRequest object replaces the global XMLHttpRequest. In your use-case, which object to use (e.g. XMLHttpRequest or MockXMLHttpRequest ) can only be decided after the `open()` method call. At that point the object is already constructed.

There is probably a way to hack this in by using a proxy object. Perhaps something like this could work (untested):
```
var ConditionalMockXhr = function() {
  // mock by default
  this.xhrDelegate = new MockXMLHttpRequest();
  
  // loop over all functions and forward them
  var _this = this;
  for (elem in this.xhrDelegate) {
    if elem === 'open' {
      this.open = function() {
	    // analyze the url and replace this.xhrDelegate with
		// a real XMLHttpRequest instance if desired and
		// forward the open() call.
	  }
	} else if typeof(this.xhrDelegate[elem]) == 'function' {
	  // regular case
      this[elem] = function() {
	    _this.xhrDelegate[elem].apply(_this.xhrDelegate, arguments);
	  }
    }
  }
}

global.XMLHttpRequest = ConditionalMockXhr;
```

In any case, this library is meant for use in tests so I would suggest that you rethink your testing strategy if possible so it does not rely on actual XMLHttpRequest requests. These can fail if, for example, the network is down.
