### ISSUE TITLE
Add support for PATCH http method

### ISSUE THREAD

**Issue by jirihybek** [berniegp/mock-xmlhttprequest#15]
**Is this issue a *feature* request or a *bug* report?**

Bug & Feature

**What is the current behavior?**

When XHR request is send with `PATCH` http method it is not recognized and an error is returned.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Yes, the official list of HTTP methods contains the PATCH method, see:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

```typescript
const server = MockXMLHttpRequest.newServer({
	patch: [
		"/api/v1/test/patch",
		{
			status: 204,
			headers: {},
		}
	]
}).install();
```

**What is the expected behavior?**

To properly process PATCH method.

**Environment in which you encounter the issue:**

- mock-xmlhttprequest version: 4.4.1
- Node.js version: v8.12.0
- OS version: OSX 10.14.6

**Did this work in a previous version of mock-xmlhttprequest (which)?**

Don't know.

**Do you intend to provide a pull request to address this issue?**

Yes.

**Solution:**

To add `PATCH` method to the `upperCaseMethods` array in `Util.js` file - see https://github.com/berniegp/mock-xmlhttprequest/blob/master/src/Utils.js#L48

**Comment by berniegp** [comment]
While you are totally right that the verbs you mentioned are official HTTP methods, the XMLHttpRequest spec has [very specific treatment of method names](https://fetch.spec.whatwg.org/#concept-method-normalize). Here is the relevant quote:

> To normalize a method, if it is a byte-case-insensitive match for `DELETE`, `GET`, `HEAD`, `OPTIONS`, `POST`, or `PUT`, byte-uppercase it. 

> Using `patch` is highly likely to result in a `405 Method Not Allowed`. `PATCH` is much more likely to succeed.

Since this library aims to follow the spec as closely as possible, the `patch` method can't be automatically uppercased.

However, I suspect that your test can probably be fixed by changing the server to an uppercase PATCH method like so:

```typescript
const server = MockXMLHttpRequest.newServer({
	PATCH: [
		"/api/v1/test/patch",
		{
			status: 204,
			headers: {},
		}
	]
}).install();
```

If you want to mock a server that responds to both PATCH and patch methods, you can do this instead:

```typescript
const server = MockXMLHttpRequest.newServer({
	patch: [
		"/api/v1/test/patch",
		{
			status: 204,
			headers: {},
		}
	],
	PATCH: [
		"/api/v1/test/patch",
		{
			status: 204,
			headers: {},
		}
	]
}).install();
```

**Comment by jirihybek** [comment]
Thank You for the explanation, now I see the difference. The solution with specifying `PATCH` in uppercase works well. Closing the issue.
