### ISSUE TITLE
setTimeout used internally

### ISSUE THREAD

**Issue by DaveStein** [berniegp/mock-xmlhttprequest#29]
**Is this issue a *feature* request or a *bug* report?**
Feature request to prevent bugs? Not sure how you would qualify this

**What is the current behavior?**
The internals of this package uses setTimeout, maybe to simulate async behavior skipping a tick? It's common to mock out setTimeout such as within `jest` folks use `jest.useFakeTimers()`. Doing so makes this library stall when making an XHR request.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Mock setTimeout to not run until you say so
2. Run test

**What is the expected behavior?**
Mocking window globals should not impact test runner

**Environment in which you encounter the issue:**

- mock-xmlhttprequest version: 7.0.4
- Node.js version: 14.17.5
- OS version: Mac

**Did this work in a previous version of mock-xmlhttprequest (which)?**
Not that I'm aware

**Do you intend to provide a pull request to address this issue?**
I honestly switched to another mock engine because this was impacting a number of tests after we realized we mistakenly had setTimeout actually running in our suite.

**Comment by berniegp** [comment]
This is expected behavior at the moment and documented:
>Request handlers are invoked in a different call stack (using setTimeout()) than the one that called send() on the XMLHttpRequest. 

The library needs a way to schedule the request handlers for execution in a separate callstack than the one that initiated the request (i.e. the test case) or otherwise everything becomes synchronous which doesn't match the real execution environment of XMLHttpRequest. The only way I know to do this is `setTimeout`.

However I understand the issue you are facing. How does the other framework handle this requirement of scheduling request handlers to execute later? I can see 2 options:
1. Provide an option to execute request handler callbacks synchronously
2. Accept a user-supplied replacement for `setTimeout` that gives the user full control. This could be for example passing in a saved "real" version of `setTimeout` while the global one is mocked.

**Comment by DaveStein** [comment]
@berniegp if you return a promise that is instantly resolved I believe that is the same behavior as an end user would expect. It's something that if I don't use `await` I will get a pending promise so I'm still forced to be sure I am writing my code for async properly.

**Comment by berniegp** [comment]
Great idea. I tried it out and it seems to work. I need to do some more work to update dependencies and the nodejs version. Some things now fail for some reason and I didn't have enough time today to finish debugging it.

**Comment by berniegp** [comment]
This is fixed in v8.0.0.
